import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import CurrentSong from "./components/CurrentSong";
import SongProvider from "./contexts/SongContext";

export const metadata = {
  title: "Saintly Sounds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SongProvider>
          <Navbar />
          <CurrentSong />
          <Footer />
          {children}
        </SongProvider>
      </body>
    </html>
  );
}
